### PR TITLE
Add SBWT construction algorithm that runs fully in-memory

### PR DESCRIPTION
**Pull request by tmaklin**
This adds the `BitPackedKmerSortingMem` construction algorithm that runs entirely in memory and is parallelised using rayon iterators. The algorithm can be enabled by enabling the `bpks-mem` feature. The memory implementation is also somewhat easier to follow than the on-disk construction code. Performance should be comparable or better if enough RAM is available.

Details:
- Moved the kmer.rs file from bitpacked_kmer_sorting to crate root since it's used in both algorithms.
- Implementation of the in-memory construction is in the bitpacked_kmer_sorting_mem folder.
- Adds a new algorithm BitPackedKmerSortingMem to builder.rs.
- Adds the same tests used for BitPackedKmerSorting for BitPackedKmerSortingMem.
- Silence some dead code warnings from the compiler.

Note that BitPackedKmerSortingMem does not have the temp_dir method (not needed) or the mem_gb method (runs 100% in memory). The algorithm does not do anything with the n_threads argument, either, as the number of threads is given by the rayon thread pool that should be initialised outside of the algorithm. These mean that the algorithm is not a true drop-in replacement for the temporary disk space algorithm although the syntax is similar.

### CODE REVIEW

**Comment by jnalanko** [comment]
Holy crap, this is huge! I need some time to review all of this before merging, but already thank you so much for the effort!

**Comment by tmaklin** [comment]
No worries, and this was actually pretty fun to implement!

**Comment by tmaklin** [comment]
btw can you also merge this https://github.com/jnalanko/simple-sds-sbwt/pull/1 when you review this pull request, it's required to make SBWT run without issues when targeting webassembly and the only change is explicitly declaring a usize as u64.

**Comment by jnalanko** [comment]
Merging. There is one issue in this patch which I'll fix after this: the LCS array is not bitcompressed. The code still works, but the index uses much more space than it needs to.

**Pull request merged**
